alias d="docker"
alias dc="docker-compose"
alias dp="docker ps"
alias dpa="docker ps -a"
alias ds="docker stop"
alias e="less"
alias g="git"
alias l="ls -lha --color"
alias mk="minikube"
alias kc="kubectl"
alias pg="pgrep -ifl"
alias v="nvim"
alias sv="sudo nvim"
alias s="sudo"

alias kga="kubectl get all"
alias sk="skaffold"
alias sdp="skaffold dev --port-forward"

alias dn="dotnet"
alias db="dotnet build"
alias dr="dotnet run"
alias da="dotnet add"

